# Generated by Django 5.0.4 on 2024-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_recipi_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipi',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
