# Generated by Django 5.0.4 on 2024-05-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_recipi_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipi',
            name='recipi_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
