# Generated by Django 5.0.4 on 2024-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_recipi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipi',
            name='recipi_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
